// <auto-generated />
using System;
using AssetManagement.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AssetManagement.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260915223452_AddIdentityAndOrganization")]
    partial class AddIdentityAndOrganization
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AssetManagement.Domain.Identity.Permission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("Module")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Module", "Action")
                        .IsUnique();

                    b.ToTable("Permissions", "identity");

                    b.HasData(
                        new
                        {
                            Id = new Guid("7a5d5652-a1ac-d274-95b2-44442db58ad8"),
                            Action = "Read",
                            Description = "Consultar empresas",
                            Module = "Companies"
                        },
                        new
                        {
                            Id = new Guid("e29fbec3-e214-f53c-8ca0-a2f1b8f7ca89"),
                            Action = "Create",
                            Description = "Crear empresas",
                            Module = "Companies"
                        },
                        new
                        {
                            Id = new Guid("51efca44-35f2-1107-93bc-f98c348c95ab"),
                            Action = "Update",
                            Description = "Editar y activar/desactivar empresas",
                            Module = "Companies"
                        },
                        new
                        {
                            Id = new Guid("f5af1a2f-635d-0f01-7b27-dc51f0c95192"),
                            Action = "Read",
                            Description = "Consultar la estructura organizacional",
                            Module = "Structure"
                        },
                        new
                        {
                            Id = new Guid("133339b6-9ddf-ed9e-379f-a1944a5a4335"),
                            Action = "Create",
                            Description = "Crear unidades organizacionales",
                            Module = "Structure"
                        },
                        new
                        {
                            Id = new Guid("9d3a8093-632b-8b3f-3601-d0b0a51327dd"),
                            Action = "Update",
                            Description = "Editar, mover y activar/desactivar unidades organizacionales",
                            Module = "Structure"
                        },
                        new
                        {
                            Id = new Guid("890418b1-6d85-ef64-7c23-0becce314341"),
                            Action = "Read",
                            Description = "Consultar roles",
                            Module = "Roles"
                        },
                        new
                        {
                            Id = new Guid("2fc809da-48b5-beb0-db76-a516975167ac"),
                            Action = "Create",
                            Description = "Crear roles",
                            Module = "Roles"
                        },
                        new
                        {
                            Id = new Guid("e3f62e59-b4b6-58e7-3bd0-426ea1ec4780"),
                            Action = "Update",
                            Description = "Editar y activar/desactivar roles",
                            Module = "Roles"
                        },
                        new
                        {
                            Id = new Guid("be9ac938-85f3-2cd7-2541-82e0161b6287"),
                            Action = "Duplicate",
                            Description = "Duplicar roles",
                            Module = "Roles"
                        },
                        new
                        {
                            Id = new Guid("b3645805-12fc-7766-134b-4385b7d86956"),
                            Action = "Read",
                            Description = "Consultar el catálogo de permisos",
                            Module = "Permissions"
                        },
                        new
                        {
                            Id = new Guid("f57b7bb7-caa8-d044-73b6-43d352e308a8"),
                            Action = "Manage",
                            Description = "Administrar la matriz de permisos por rol",
                            Module = "Permissions"
                        },
                        new
                        {
                            Id = new Guid("c63e9245-979e-0353-3f7f-ea5795c10cde"),
                            Action = "Read",
                            Description = "Consultar usuarios",
                            Module = "Users"
                        },
                        new
                        {
                            Id = new Guid("0b235011-5ebf-5a6a-039b-e20dd438d3ea"),
                            Action = "Update",
                            Description = "Editar el perfil de un usuario",
                            Module = "Users"
                        },
                        new
                        {
                            Id = new Guid("994cea42-d44d-409a-ddb1-757489a9eade"),
                            Action = "ManageRoles",
                            Description = "Asignar y quitar roles a usuarios",
                            Module = "Users"
                        },
                        new
                        {
                            Id = new Guid("402e4fc0-8838-b4f0-e420-adb4e3d8e15e"),
                            Action = "ManageCompanies",
                            Description = "Otorgar y revocar acceso de usuarios a empresas",
                            Module = "Users"
                        },
                        new
                        {
                            Id = new Guid("5b88cd52-8151-a321-9948-a0b6605199a8"),
                            Action = "Read",
                            Description = "Consultar activos",
                            Module = "Assets"
                        },
                        new
                        {
                            Id = new Guid("378030f9-f874-5516-c964-f51ec5510527"),
                            Action = "Create",
                            Description = "Dar de alta activos",
                            Module = "Assets"
                        },
                        new
                        {
                            Id = new Guid("76da9d34-92ae-05b8-d138-be710fadc141"),
                            Action = "Update",
                            Description = "Editar activos",
                            Module = "Assets"
                        },
                        new
                        {
                            Id = new Guid("65ef226f-e2db-3a12-0477-ab17f129d3e8"),
                            Action = "Decommission",
                            Description = "Dar de baja activos",
                            Module = "Assets"
                        },
                        new
                        {
                            Id = new Guid("59f420f8-c138-7c15-75ef-16a829e7178f"),
                            Action = "Read",
                            Description = "Consultar asignaciones",
                            Module = "Assignments"
                        },
                        new
                        {
                            Id = new Guid("36823748-f420-0165-40b3-e3e9e03e7efc"),
                            Action = "Create",
                            Description = "Crear asignaciones",
                            Module = "Assignments"
                        },
                        new
                        {
                            Id = new Guid("8a224771-1e2a-23ee-59f6-5bdd1c8571dd"),
                            Action = "Update",
                            Description = "Editar asignaciones",
                            Module = "Assignments"
                        },
                        new
                        {
                            Id = new Guid("2320c50e-22d6-4707-7a4a-015dbbf5850e"),
                            Action = "Read",
                            Description = "Consultar devoluciones",
                            Module = "Returns"
                        },
                        new
                        {
                            Id = new Guid("540d31ee-7573-cb93-c53d-eecb906d879f"),
                            Action = "Create",
                            Description = "Registrar devoluciones",
                            Module = "Returns"
                        },
                        new
                        {
                            Id = new Guid("634dffa1-d1c3-6f18-dec1-c8f7799f0d1d"),
                            Action = "Read",
                            Description = "Consultar préstamos",
                            Module = "Loans"
                        },
                        new
                        {
                            Id = new Guid("5ed43a61-1131-35f9-418e-5d734885f041"),
                            Action = "Create",
                            Description = "Registrar préstamos",
                            Module = "Loans"
                        },
                        new
                        {
                            Id = new Guid("27c19625-05a9-ed04-e019-b3aeaeecf0de"),
                            Action = "Update",
                            Description = "Editar préstamos",
                            Module = "Loans"
                        },
                        new
                        {
                            Id = new Guid("213949d4-f099-2fc0-2d4d-7c36b0e52202"),
                            Action = "Read",
                            Description = "Consultar transferencias",
                            Module = "Transfers"
                        },
                        new
                        {
                            Id = new Guid("0857a031-1328-02fd-cdd2-ede1edec414b"),
                            Action = "Create",
                            Description = "Crear transferencias",
                            Module = "Transfers"
                        },
                        new
                        {
                            Id = new Guid("7b9a501b-aca1-782e-2453-4069f9fe6b8e"),
                            Action = "Update",
                            Description = "Editar transferencias",
                            Module = "Transfers"
                        },
                        new
                        {
                            Id = new Guid("40b4fffd-9165-183c-c6bb-59bc8ae3028e"),
                            Action = "Read",
                            Description = "Consultar movimientos",
                            Module = "Movements"
                        },
                        new
                        {
                            Id = new Guid("268680ee-9be4-a63b-28ed-d2c3d6efdcad"),
                            Action = "Read",
                            Description = "Consultar solicitudes",
                            Module = "Requests"
                        },
                        new
                        {
                            Id = new Guid("30078032-4b27-50da-0761-d9aa615395b3"),
                            Action = "Create",
                            Description = "Crear solicitudes",
                            Module = "Requests"
                        },
                        new
                        {
                            Id = new Guid("8b2f8328-2079-f60b-d7d6-95cdd03d56b0"),
                            Action = "Update",
                            Description = "Editar solicitudes",
                            Module = "Requests"
                        },
                        new
                        {
                            Id = new Guid("c6ad17a7-b959-17e1-884b-ce8c45227908"),
                            Action = "Read",
                            Description = "Consultar mantenimientos",
                            Module = "Maintenance"
                        },
                        new
                        {
                            Id = new Guid("2dabb61a-3ae8-e7ce-2339-2f8a93c57166"),
                            Action = "Create",
                            Description = "Crear mantenimientos",
                            Module = "Maintenance"
                        },
                        new
                        {
                            Id = new Guid("f09c265e-84ff-7299-fb9c-be48c4a0a743"),
                            Action = "Update",
                            Description = "Editar y cerrar mantenimientos",
                            Module = "Maintenance"
                        },
                        new
                        {
                            Id = new Guid("62d5f94f-ce24-94a7-58fd-bb725f1c86ed"),
                            Action = "Read",
                            Description = "Consultar garantías",
                            Module = "Warranties"
                        },
                        new
                        {
                            Id = new Guid("3365539c-176c-9ebd-50e0-a5fcd957ed81"),
                            Action = "Create",
                            Description = "Registrar garantías",
                            Module = "Warranties"
                        },
                        new
                        {
                            Id = new Guid("96e2517c-3d27-8a06-7ee1-f62f1a7df249"),
                            Action = "Update",
                            Description = "Editar garantías",
                            Module = "Warranties"
                        },
                        new
                        {
                            Id = new Guid("d5ee8009-1ae1-1443-53dd-89f6ad932040"),
                            Action = "Read",
                            Description = "Consultar refacciones",
                            Module = "SpareParts"
                        },
                        new
                        {
                            Id = new Guid("c6acddef-defc-66bd-f092-2f4961c55029"),
                            Action = "Create",
                            Description = "Registrar refacciones",
                            Module = "SpareParts"
                        },
                        new
                        {
                            Id = new Guid("270ef0a3-09f6-ac45-8785-2e71371ca7dc"),
                            Action = "Update",
                            Description = "Editar refacciones",
                            Module = "SpareParts"
                        },
                        new
                        {
                            Id = new Guid("795066b7-6317-d5c6-f5af-d2bb4983d9e1"),
                            Action = "Read",
                            Description = "Consultar consumibles",
                            Module = "Consumables"
                        },
                        new
                        {
                            Id = new Guid("9ac2f6ca-bc4c-715c-c77d-cf0c0db277ed"),
                            Action = "Create",
                            Description = "Registrar consumibles",
                            Module = "Consumables"
                        },
                        new
                        {
                            Id = new Guid("72812ef6-fd11-a91e-eacd-e45767c1bf52"),
                            Action = "Update",
                            Description = "Editar consumibles",
                            Module = "Consumables"
                        },
                        new
                        {
                            Id = new Guid("d046fbc0-f442-19b7-74ca-adbeaf30c6c8"),
                            Action = "Read",
                            Description = "Consultar documentos",
                            Module = "Documents"
                        },
                        new
                        {
                            Id = new Guid("52d4b4b1-15c6-1e8c-598c-ad0d8df168cd"),
                            Action = "Create",
                            Description = "Cargar documentos",
                            Module = "Documents"
                        },
                        new
                        {
                            Id = new Guid("9abf5b7b-1ba0-e2d1-c8b6-056606a5de5d"),
                            Action = "Read",
                            Description = "Consultar plantillas",
                            Module = "Templates"
                        },
                        new
                        {
                            Id = new Guid("5773bc8f-342d-11cb-d06f-cae7c2ff8955"),
                            Action = "Create",
                            Description = "Crear plantillas",
                            Module = "Templates"
                        },
                        new
                        {
                            Id = new Guid("38045db3-c437-2c0d-9b9f-ef5c4754d976"),
                            Action = "Update",
                            Description = "Editar y publicar plantillas",
                            Module = "Templates"
                        },
                        new
                        {
                            Id = new Guid("463e11ac-d988-e061-b8d1-e2af274d1408"),
                            Action = "Read",
                            Description = "Consultar reportes por empresa",
                            Module = "Reports"
                        },
                        new
                        {
                            Id = new Guid("ed65ea32-ae1f-14e3-ff0b-2a75bfd0a393"),
                            Action = "ReadConsolidated",
                            Description = "Consultar reportes consolidados entre empresas",
                            Module = "Reports"
                        },
                        new
                        {
                            Id = new Guid("9b30f027-273b-d2d8-264d-c800598aa857"),
                            Action = "Export",
                            Description = "Exportar reportes",
                            Module = "Reports"
                        },
                        new
                        {
                            Id = new Guid("70750688-5a74-757a-9cd8-44bda7b994a5"),
                            Action = "Read",
                            Description = "Consultar el registro de auditoría",
                            Module = "Audit"
                        },
                        new
                        {
                            Id = new Guid("9ef45691-7abd-42c2-3dda-5ffb8bc7eda6"),
                            Action = "Read",
                            Description = "Consultar catálogos",
                            Module = "Catalogs"
                        },
                        new
                        {
                            Id = new Guid("d8235c70-53e7-80a3-24cf-bd2bb89d0b04"),
                            Action = "Create",
                            Description = "Crear entradas de catálogo",
                            Module = "Catalogs"
                        },
                        new
                        {
                            Id = new Guid("3be03333-5582-c4c2-49ef-412e3ff8a424"),
                            Action = "Update",
                            Description = "Editar entradas de catálogo",
                            Module = "Catalogs"
                        },
                        new
                        {
                            Id = new Guid("724181e6-2f47-16c3-ad02-0a49875b2709"),
                            Action = "Read",
                            Description = "Consultar lotes de importación",
                            Module = "Imports"
                        },
                        new
                        {
                            Id = new Guid("bb101cae-8dbb-7955-aa73-6ce19633d581"),
                            Action = "Create",
                            Description = "Iniciar importaciones masivas",
                            Module = "Imports"
                        },
                        new
                        {
                            Id = new Guid("e3237316-9a5c-30f2-e041-f06a00de5f8b"),
                            Action = "Create",
                            Description = "Generar exportaciones",
                            Module = "Exports"
                        },
                        new
                        {
                            Id = new Guid("fa13fc8c-2340-d2f5-fa21-7f64575be3f9"),
                            Action = "Read",
                            Description = "Consultar flujos y solicitudes de aprobación",
                            Module = "Approvals"
                        },
                        new
                        {
                            Id = new Guid("30130c59-70e4-7722-0d12-b20ff25b183e"),
                            Action = "Configure",
                            Description = "Configurar flujos de aprobación",
                            Module = "Approvals"
                        },
                        new
                        {
                            Id = new Guid("d84f3d31-95fb-a3ae-7fa3-b82d08357951"),
                            Action = "Approve",
                            Description = "Aprobar o rechazar solicitudes",
                            Module = "Approvals"
                        },
                        new
                        {
                            Id = new Guid("2a7474be-e80c-c46f-f853-9b8e966b3e7d"),
                            Action = "Reject",
                            Description = "Rechazar solicitudes",
                            Module = "Approvals"
                        },
                        new
                        {
                            Id = new Guid("c4216206-ff04-228e-79a4-bae418708795"),
                            Action = "Read",
                            Description = "Consultar configuración del sistema",
                            Module = "Configuration"
                        },
                        new
                        {
                            Id = new Guid("1df2c2f0-ee0e-4444-93de-668ed2227c53"),
                            Action = "Update",
                            Description = "Editar configuración del sistema",
                            Module = "Configuration"
                        });
                });

            modelBuilder.Entity("AssetManagement.Domain.Identity.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Roles", "identity");
                });

            modelBuilder.Entity("AssetManagement.Domain.Identity.RolePermission", b =>
                {
                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PermissionId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("RoleId", "PermissionId");

                    b.HasIndex("PermissionId");

                    b.ToTable("RolePermissions", "identity");
                });

            modelBuilder.Entity("AssetManagement.Domain.Identity.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("nvarchar(320)");

                    b.Property<Guid>("EntraObjectId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LastLoginAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("Email");

                    b.HasIndex("EntraObjectId")
                        .IsUnique();

                    b.ToTable("Users", "identity");
                });

            modelBuilder.Entity("AssetManagement.Domain.Identity.UserCompany", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("GrantedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("UserId", "CompanyId");

                    b.ToTable("UserCompanies", "identity");
                });

            modelBuilder.Entity("AssetManagement.Domain.Identity.UserRole", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("AssignedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid?>("AssignedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("UserRoles", "identity");
                });

            modelBuilder.Entity("AssetManagement.Domain.Organization.Company", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("BaseCurrency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("LegalName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("TaxId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TimeZone")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("TradeName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("TaxId")
                        .IsUnique();

                    b.ToTable("Companies", "organization");
                });

            modelBuilder.Entity("AssetManagement.Domain.Organization.OrgUnit", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid>("OrgUnitTypeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ParentOrgUnitId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("OrgUnitTypeId");

                    b.HasIndex("ParentOrgUnitId");

                    b.HasIndex("CompanyId", "Code")
                        .IsUnique();

                    b.HasIndex("CompanyId", "IsActive");

                    b.ToTable("OrgUnits", "organization");
                });

            modelBuilder.Entity("AssetManagement.Domain.Organization.OrgUnitType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("OrgUnitTypes", "organization");

                    b.HasData(
                        new
                        {
                            Id = new Guid("2a8c40c9-27ba-15e0-84e4-ce2b3058a07b"),
                            Code = "BusinessUnit",
                            IsActive = true,
                            Name = "Unidad de negocio"
                        },
                        new
                        {
                            Id = new Guid("ac8bc210-f0f6-8e26-81b2-7d66d23365f9"),
                            Code = "Direction",
                            IsActive = true,
                            Name = "Dirección"
                        },
                        new
                        {
                            Id = new Guid("128bf7a4-eaee-c125-4264-41a096400c5d"),
                            Code = "Management",
                            IsActive = true,
                            Name = "Gerencia"
                        },
                        new
                        {
                            Id = new Guid("ee2babf1-dc51-68c8-3a7d-c5e2cdf92f96"),
                            Code = "Department",
                            IsActive = true,
                            Name = "Departamento"
                        },
                        new
                        {
                            Id = new Guid("f39ccc0b-dd33-bfeb-2c55-34ff08570cb0"),
                            Code = "Area",
                            IsActive = true,
                            Name = "Área"
                        },
                        new
                        {
                            Id = new Guid("97350561-7bb1-02e8-7f7d-9a13c1d769f7"),
                            Code = "Team",
                            IsActive = true,
                            Name = "Equipo"
                        },
                        new
                        {
                            Id = new Guid("879fb8c5-3bed-5ae1-0148-44c616d61c3b"),
                            Code = "Branch",
                            IsActive = true,
                            Name = "Sucursal"
                        },
                        new
                        {
                            Id = new Guid("d8ac22ee-3164-46dc-42db-b7e2251113f3"),
                            Code = "Location",
                            IsActive = true,
                            Name = "Ubicación física"
                        },
                        new
                        {
                            Id = new Guid("851df337-7b61-5a0d-c862-7f4d945c0da5"),
                            Code = "Warehouse",
                            IsActive = true,
                            Name = "Almacén"
                        },
                        new
                        {
                            Id = new Guid("5becbc5a-1874-fe4b-343f-7664304fcd0e"),
                            Code = "DataCenter",
                            IsActive = true,
                            Name = "Centro de datos"
                        },
                        new
                        {
                            Id = new Guid("c7376946-92c6-23ba-690e-165ea161977e"),
                            Code = "Project",
                            IsActive = true,
                            Name = "Proyecto"
                        });
                });

            modelBuilder.Entity("AssetManagement.Domain.Identity.RolePermission", b =>
                {
                    b.HasOne("AssetManagement.Domain.Identity.Permission", null)
                        .WithMany()
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AssetManagement.Domain.Identity.Role", null)
                        .WithMany("RolePermissions")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AssetManagement.Domain.Identity.UserCompany", b =>
                {
                    b.HasOne("AssetManagement.Domain.Identity.User", null)
                        .WithMany("UserCompanies")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AssetManagement.Domain.Identity.UserRole", b =>
                {
                    b.HasOne("AssetManagement.Domain.Identity.Role", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AssetManagement.Domain.Identity.User", null)
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("AssetManagement.Domain.Organization.OrgUnit", b =>
                {
                    b.HasOne("AssetManagement.Domain.Organization.OrgUnitType", null)
                        .WithMany()
                        .HasForeignKey("OrgUnitTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AssetManagement.Domain.Organization.OrgUnit", null)
                        .WithMany()
                        .HasForeignKey("ParentOrgUnitId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("AssetManagement.Domain.Identity.Role", b =>
                {
                    b.Navigation("RolePermissions");
                });

            modelBuilder.Entity("AssetManagement.Domain.Identity.User", b =>
                {
                    b.Navigation("UserCompanies");

                    b.Navigation("UserRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
